name: WiFiGuard
description: "Wi-Fi Guard network vulnerability scanner"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  network_info_plus: ^6.1.1
  dart_ping: ^9.0.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  speed_test_dart: ^1.0.5+0
  syncfusion_flutter_gauges: ^29.1.33
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^19.0.0
  flutter_foreground_task: ^8.17.0
  process_run: ^1.2.2+1
  chaquopy: ^0.0.20
  font_awesome_flutter: ^10.8.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/scan.py

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/favicon.png"